export interface Problem {
  id: string;
  num: number;
  title: string;
  diff: "easy" | "medium" | "hard";
  pattern: string;
  url: string;
  descHtml: string;
  starter: string;
}

const sol = (sig: string) => `class Solution {\n    ${sig} {\n        \n    }\n}`;
const solNode = (note: string, sig: string) => `// Definition: ${note}\n${sol(sig)}`;
const TN = "TreeNode { int val; TreeNode left, right; }";
const LN = "ListNode { int val; ListNode next; }";

// Ported verbatim from mock-interview-room.html's `const STARTERS` map.
const STARTERS: Record<string, string> = {
  // Arrays & Hashing
  "two-sum": sol("public int[] twoSum(int[] nums, int target)"),
  "contains-duplicate": sol("public boolean containsDuplicate(int[] nums)"),
  "valid-anagram": sol("public boolean isAnagram(String s, String t)"),
  "group-anagrams": sol("public List<List<String>> groupAnagrams(String[] strs)"),
  "top-k-frequent-elements": sol("public int[] topKFrequent(int[] nums, int k)"),
  "product-of-array-except-self": sol("public int[] productExceptSelf(int[] nums)"),
  // Two Pointers
  "valid-palindrome": sol("public boolean isPalindrome(String s)"),
  "two-sum-ii-input-array-is-sorted": sol("public int[] twoSum(int[] numbers, int target)"),
  "3sum": sol("public List<List<Integer>> threeSum(int[] nums)"),
  "container-with-most-water": sol("public int maxArea(int[] height)"),
  "trapping-rain-water": sol("public int trap(int[] height)"),
  // Sliding Window
  "best-time-to-buy-and-sell-stock": sol("public int maxProfit(int[] prices)"),
  "longest-substring-without-repeating-characters": sol("public int lengthOfLongestSubstring(String s)"),
  "longest-repeating-character-replacement": sol("public int characterReplacement(String s, int k)"),
  "permutation-in-string": sol("public boolean checkInclusion(String s1, String s2)"),
  "minimum-window-substring": sol("public String minWindow(String s, String t)"),
  // Stack
  "valid-parentheses": sol("public boolean isValid(String s)"),
  "min-stack":
    "class MinStack {\n    public MinStack() {\n        \n    }\n    public void push(int val) {\n        \n    }\n    public void pop() {\n        \n    }\n    public int top() {\n        \n    }\n    public int getMin() {\n        \n    }\n}",
  "evaluate-reverse-polish-notation": sol("public int evalRPN(String[] tokens)"),
  "daily-temperatures": sol("public int[] dailyTemperatures(int[] temperatures)"),
  "car-fleet": sol("public int carFleet(int target, int[] position, int[] speed)"),
  "largest-rectangle-in-histogram": sol("public int largestRectangleArea(int[] heights)"),
  // Binary Search
  "binary-search": sol("public int search(int[] nums, int target)"),
  "search-a-2d-matrix": sol("public boolean searchMatrix(int[][] matrix, int target)"),
  "find-minimum-in-rotated-sorted-array": sol("public int findMin(int[] nums)"),
  "search-in-rotated-sorted-array": sol("public int search(int[] nums, int target)"),
  "koko-eating-bananas": sol("public int minEatingSpeed(int[] piles, int h)"),
  "median-of-two-sorted-arrays": sol("public double findMedianSortedArrays(int[] nums1, int[] nums2)"),
  // Linked List
  "reverse-linked-list": solNode(LN, "public ListNode reverseList(ListNode head)"),
  "merge-two-sorted-lists": solNode(LN, "public ListNode mergeTwoLists(ListNode list1, ListNode list2)"),
  "linked-list-cycle": solNode(LN, "public boolean hasCycle(ListNode head)"),
  "remove-nth-node-from-end-of-list": solNode(LN, "public ListNode removeNthFromEnd(ListNode head, int n)"),
  "reorder-list": solNode(LN, "public void reorderList(ListNode head)"),
  "lru-cache":
    "class LRUCache {\n    public LRUCache(int capacity) {\n        \n    }\n    public int get(int key) {\n        \n    }\n    public void put(int key, int value) {\n        \n    }\n}",
  "merge-k-sorted-lists": solNode(LN, "public ListNode mergeKLists(ListNode[] lists)"),
  // Trees
  "invert-binary-tree": solNode(TN, "public TreeNode invertTree(TreeNode root)"),
  "maximum-depth-of-binary-tree": solNode(TN, "public int maxDepth(TreeNode root)"),
  "subtree-of-another-tree": solNode(TN, "public boolean isSubtree(TreeNode root, TreeNode subRoot)"),
  "binary-tree-level-order-traversal": solNode(TN, "public List<List<Integer>> levelOrder(TreeNode root)"),
  "validate-binary-search-tree": solNode(TN, "public boolean isValidBST(TreeNode root)"),
  "lowest-common-ancestor-of-a-binary-search-tree": solNode(
    TN,
    "public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q)"
  ),
  "kth-smallest-element-in-a-bst": solNode(TN, "public int kthSmallest(TreeNode root, int k)"),
  "construct-binary-tree-from-preorder-and-inorder-traversal": solNode(
    TN,
    "public TreeNode buildTree(int[] preorder, int[] inorder)"
  ),
  "serialize-and-deserialize-binary-tree":
    "// Definition: " +
    TN +
    "\npublic class Codec {\n    public String serialize(TreeNode root) {\n        \n    }\n    public TreeNode deserialize(String data) {\n        \n    }\n}",
  "binary-tree-maximum-path-sum": solNode(TN, "public int maxPathSum(TreeNode root)"),
  // Tries
  "implement-trie-prefix-tree":
    "class Trie {\n    public Trie() {\n        \n    }\n    public void insert(String word) {\n        \n    }\n    public boolean search(String word) {\n        \n    }\n    public boolean startsWith(String prefix) {\n        \n    }\n}",
  "design-add-and-search-words-data-structure":
    "class WordDictionary {\n    public WordDictionary() {\n        \n    }\n    public void addWord(String word) {\n        \n    }\n    public boolean search(String word) {\n        \n    }\n}",
  "word-search-ii": sol("public List<String> findWords(char[][] board, String[] words)"),
  // Heaps / Priority Queue
  "kth-largest-element-in-a-stream":
    "class KthLargest {\n    public KthLargest(int k, int[] nums) {\n        \n    }\n    public int add(int val) {\n        \n    }\n}",
  "last-stone-weight": sol("public int lastStoneWeight(int[] stones)"),
  "k-closest-points-to-origin": sol("public int[][] kClosest(int[][] points, int k)"),
  "kth-largest-element-in-an-array": sol("public int findKthLargest(int[] nums, int k)"),
  "task-scheduler": sol("public int leastInterval(char[] tasks, int n)"),
  "find-median-from-data-stream":
    "class MedianFinder {\n    public MedianFinder() {\n        \n    }\n    public void addNum(int num) {\n        \n    }\n    public double findMedian() {\n        \n    }\n}",
  // Backtracking
  subsets: sol("public List<List<Integer>> subsets(int[] nums)"),
  "combination-sum": sol("public List<List<Integer>> combinationSum(int[] candidates, int target)"),
  permutations: sol("public List<List<Integer>> permute(int[] nums)"),
  "word-search": sol("public boolean exist(char[][] board, String word)"),
  "palindrome-partitioning": sol("public List<List<String>> partition(String s)"),
  "n-queens": sol("public List<List<String>> solveNQueens(int n)"),
  // Graphs
  "number-of-islands": sol("public int numIslands(char[][] grid)"),
  "flood-fill": sol("public int[][] floodFill(int[][] image, int sr, int sc, int color)"),
  "clone-graph": solNode("Node { int val; List<Node> neighbors; }", "public Node cloneGraph(Node node)"),
  "rotting-oranges": sol("public int orangesRotting(int[][] grid)"),
  "pacific-atlantic-water-flow": sol("public List<List<Integer>> pacificAtlantic(int[][] heights)"),
  "course-schedule": sol("public boolean canFinish(int numCourses, int[][] prerequisites)"),
  "number-of-connected-components-in-an-undirected-graph": sol(
    "public int countComponents(int n, int[][] edges)"
  ),
  "graph-valid-tree": sol("public boolean validTree(int n, int[][] edges)"),
  "word-ladder": sol("public int ladderLength(String beginWord, String endWord, List<String> wordList)"),
  "alien-dictionary": sol("public String alienOrder(String[] words)"),
  // Intervals
  "merge-intervals": sol("public int[][] merge(int[][] intervals)"),
  "insert-interval": sol("public int[][] insert(int[][] intervals, int[] newInterval)"),
  "non-overlapping-intervals": sol("public int eraseOverlapIntervals(int[][] intervals)"),
  "meeting-rooms-ii": sol("public int minMeetingRooms(int[][] intervals)"),
  // Greedy
  "maximum-subarray": sol("public int maxSubArray(int[] nums)"),
  "jump-game": sol("public boolean canJump(int[] nums)"),
  "jump-game-ii": sol("public int jump(int[] nums)"),
  "gas-station": sol("public int canCompleteCircuit(int[] gas, int[] cost)"),
  "hand-of-straights": sol("public boolean isNStraightHand(int[] hand, int groupSize)"),
  // Dynamic Programming
  "climbing-stairs": sol("public int climbStairs(int n)"),
  "house-robber": sol("public int rob(int[] nums)"),
  "house-robber-ii": sol("public int rob(int[] nums)"),
  "coin-change": sol("public int coinChange(int[] coins, int amount)"),
  "longest-increasing-subsequence": sol("public int lengthOfLIS(int[] nums)"),
  "word-break": sol("public boolean wordBreak(String s, List<String> wordDict)"),
  "decode-ways": sol("public int numDecodings(String s)"),
  "longest-palindromic-substring": sol("public String longestPalindrome(String s)"),
  "unique-paths": sol("public int uniquePaths(int m, int n)"),
  "longest-common-subsequence": sol("public int longestCommonSubsequence(String text1, String text2)"),
  // Bit Manipulation / Math
  "single-number": sol("public int singleNumber(int[] nums)"),
  "number-of-1-bits": sol("public int hammingWeight(int n)"),
  "counting-bits": sol("public int[] countBits(int n)"),
  "missing-number": sol("public int missingNumber(int[] nums)"),
  "reverse-bits": sol("public int reverseBits(int n)"),
};

interface Raw {
  num: number;
  diff: Problem["diff"];
  pattern: string;
  slug: string;
  title: string;
  desc: string;
  ex: string;
  con: string;
}

function build(r: Raw): Problem {
  const url = `https://leetcode.com/problems/${r.slug}/`;
  let descHtml = `<p>${r.desc}</p>`;
  if (r.ex) descHtml += `<h4>Example</h4><pre>${r.ex}</pre>`;
  if (r.con) descHtml += `<h4>Constraints</h4><p>${r.con}</p>`;
  let starter = STARTERS[r.slug] || `class Solution {\n    // #${r.num} ${r.title}\n}`;
  if (/List<|Map<|Set<|Deque|PriorityQueue/.test(starter)) starter = "import java.util.*;\n\n" + starter;
  return { id: r.slug, num: r.num, title: r.title, diff: r.diff, pattern: r.pattern, url, descHtml, starter };
}

// Ported verbatim from mock-interview-room.html's `const PROBLEMS` array (P(...) calls).
const RAW: Raw[] = [
  // ---- Arrays & Hashing ----
  {
    num: 1,
    diff: "easy",
    pattern: "Arrays & Hashing",
    slug: "two-sum",
    title: "Two Sum",
    desc: "Given an integer array and a target, return the indices of the two values that add up to the target.",
    ex: "nums = [2,7,11,15], target = 9  ->  [0,1]   (2 + 7 = 9)",
    con: "Exactly one valid answer; you may not reuse an element.",
  },
  {
    num: 217,
    diff: "easy",
    pattern: "Arrays & Hashing",
    slug: "contains-duplicate",
    title: "Contains Duplicate",
    desc: "Return true if any value appears at least twice in the array, and false if every element is distinct.",
    ex: "[1,2,3,1] -> true\n[1,2,3,4] -> false",
    con: "",
  },
  {
    num: 242,
    diff: "easy",
    pattern: "Arrays & Hashing",
    slug: "valid-anagram",
    title: "Valid Anagram",
    desc: "Return true if string t is an anagram of s — the same characters with the same counts, reordered.",
    ex: 's = "anagram", t = "nagaram" -> true\ns = "rat", t = "car" -> false',
    con: "",
  },
  {
    num: 49,
    diff: "medium",
    pattern: "Arrays & Hashing",
    slug: "group-anagrams",
    title: "Group Anagrams",
    desc: "Group the strings that are anagrams of each other. Return the groups in any order.",
    ex: '["eat","tea","tan","ate","nat","bat"]\n-> [["bat"],["nat","tan"],["ate","eat","tea"]]',
    con: "Lowercase English letters.",
  },
  {
    num: 347,
    diff: "medium",
    pattern: "Arrays & Hashing",
    slug: "top-k-frequent-elements",
    title: "Top K Frequent Elements",
    desc: "Return the k most frequent elements, in any order. Aim to beat O(n log n).",
    ex: "nums = [1,1,1,2,2,3], k = 2 -> [1,2]",
    con: "",
  },
  {
    num: 238,
    diff: "medium",
    pattern: "Arrays & Hashing",
    slug: "product-of-array-except-self",
    title: "Product of Array Except Self",
    desc: "Return an array where each position holds the product of every other element. No division, O(n) time.",
    ex: "[1,2,3,4] -> [24,12,8,6]",
    con: "",
  },
  // ---- Two Pointers ----
  {
    num: 125,
    diff: "easy",
    pattern: "Two Pointers",
    slug: "valid-palindrome",
    title: "Valid Palindrome",
    desc: "Return true if the string is a palindrome, considering only alphanumeric characters and ignoring case.",
    ex: '"A man, a plan, a canal: Panama" -> true\n"race a car" -> false',
    con: "",
  },
  {
    num: 167,
    diff: "medium",
    pattern: "Two Pointers",
    slug: "two-sum-ii-input-array-is-sorted",
    title: "Two Sum II — Input Array Is Sorted",
    desc: "The array is sorted ascending. Return the 1-based indices of the two numbers that sum to the target.",
    ex: "numbers = [2,7,11,15], target = 9 -> [1,2]",
    con: "Exactly one solution; O(1) extra space.",
  },
  {
    num: 15,
    diff: "medium",
    pattern: "Two Pointers",
    slug: "3sum",
    title: "3Sum",
    desc: "Return all unique triplets [a,b,c] from the array with a + b + c = 0. No duplicate triplets.",
    ex: "[-1,0,1,2,-1,-4] -> [[-1,-1,2],[-1,0,1]]",
    con: "",
  },
  {
    num: 11,
    diff: "medium",
    pattern: "Two Pointers",
    slug: "container-with-most-water",
    title: "Container With Most Water",
    desc: "Each value is a vertical line height. Pick two lines that with the x-axis hold the most water; return that area.",
    ex: "[1,8,6,2,5,4,8,3,7] -> 49",
    con: "",
  },
  {
    num: 42,
    diff: "hard",
    pattern: "Two Pointers",
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    desc: "Given non-negative bar heights of width 1, compute how much rain water is trapped after it rains.",
    ex: "[0,1,0,2,1,0,1,3,2,1,2,1] -> 6",
    con: "",
  },
  // ---- Sliding Window ----
  {
    num: 121,
    diff: "easy",
    pattern: "Sliding Window",
    slug: "best-time-to-buy-and-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    desc: "prices[i] is the price on day i. Buy once and sell on a later day for the maximum profit; return 0 if impossible.",
    ex: "[7,1,5,3,6,4] -> 5   (buy at 1, sell at 6)",
    con: "",
  },
  {
    num: 3,
    diff: "medium",
    pattern: "Sliding Window",
    slug: "longest-substring-without-repeating-characters",
    title: "Longest Substring Without Repeating Characters",
    desc: "Return the length of the longest substring that has no repeating characters.",
    ex: '"abcabcbb" -> 3   ("abc")\n"bbbbb" -> 1',
    con: "",
  },
  {
    num: 424,
    diff: "medium",
    pattern: "Sliding Window",
    slug: "longest-repeating-character-replacement",
    title: "Longest Repeating Character Replacement",
    desc: "You may replace up to k characters. Return the length of the longest substring of a single repeated letter achievable.",
    ex: 's = "AABABBA", k = 1 -> 4',
    con: "",
  },
  {
    num: 567,
    diff: "medium",
    pattern: "Sliding Window",
    slug: "permutation-in-string",
    title: "Permutation in String",
    desc: "Return true if s2 contains any permutation of s1 as a contiguous substring.",
    ex: 's1 = "ab", s2 = "eidbaooo" -> true   ("ba")',
    con: "",
  },
  {
    num: 76,
    diff: "hard",
    pattern: "Sliding Window",
    slug: "minimum-window-substring",
    title: "Minimum Window Substring",
    desc: 'Return the smallest substring of s that contains every character of t (including duplicates), or "" if none exists.',
    ex: 's = "ADOBECODEBANC", t = "ABC" -> "BANC"',
    con: "",
  },
  // ---- Stack ----
  {
    num: 20,
    diff: "easy",
    pattern: "Stack",
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    desc: "Given a string of just ()[]{}, return true if every bracket is closed by the matching type in the correct order.",
    ex: '"()[]{}" -> true\n"(]" -> false\n"([)]" -> false',
    con: "",
  },
  {
    num: 155,
    diff: "medium",
    pattern: "Stack",
    slug: "min-stack",
    title: "Min Stack",
    desc: "Design a stack supporting push, pop, top, and getMin — every operation in O(1).",
    ex: "push(-2), push(0), push(-3), getMin() -> -3, pop(), top() -> 0, getMin() -> -2",
    con: "",
  },
  {
    num: 150,
    diff: "medium",
    pattern: "Stack",
    slug: "evaluate-reverse-polish-notation",
    title: "Evaluate Reverse Polish Notation",
    desc: "Evaluate an arithmetic expression in Reverse Polish (postfix) Notation with + - * /. Division truncates toward zero.",
    ex: '["2","1","+","3","*"] -> 9   ((2 + 1) * 3)',
    con: "",
  },
  {
    num: 739,
    diff: "medium",
    pattern: "Stack",
    slug: "daily-temperatures",
    title: "Daily Temperatures",
    desc: "For each day, return how many days you must wait for a warmer temperature (0 if there is none).",
    ex: "[73,74,75,71,69,72,76,73] -> [1,1,4,2,1,1,0,0]",
    con: "",
  },
  {
    num: 853,
    diff: "medium",
    pattern: "Stack",
    slug: "car-fleet",
    title: "Car Fleet",
    desc: "Cars head to a target at given positions and speeds; a faster car catches up but cannot pass, forming a fleet. Return the number of fleets that reach the target.",
    ex: "target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3] -> 3",
    con: "",
  },
  {
    num: 84,
    diff: "hard",
    pattern: "Stack",
    slug: "largest-rectangle-in-histogram",
    title: "Largest Rectangle in Histogram",
    desc: "Given bar heights of width 1, return the area of the largest rectangle that fits within the histogram.",
    ex: "[2,1,5,6,2,3] -> 10",
    con: "",
  },
  // ---- Binary Search ----
  {
    num: 704,
    diff: "easy",
    pattern: "Binary Search",
    slug: "binary-search",
    title: "Binary Search",
    desc: "Return the index of target in a sorted array of distinct integers, or -1 if absent. Run in O(log n).",
    ex: "nums = [-1,0,3,5,9,12], target = 9 -> 4",
    con: "",
  },
  {
    num: 74,
    diff: "medium",
    pattern: "Binary Search",
    slug: "search-a-2d-matrix",
    title: "Search a 2D Matrix",
    desc: "Each row is sorted and each row's first value is greater than the previous row's last. Return true if target is present, in O(log(m*n)).",
    ex: "target = 3 in [[1,3,5,7],[10,11,16,20],[23,30,34,60]] -> true",
    con: "",
  },
  {
    num: 153,
    diff: "medium",
    pattern: "Binary Search",
    slug: "find-minimum-in-rotated-sorted-array",
    title: "Find Minimum in Rotated Sorted Array",
    desc: "A sorted array of distinct values was rotated. Return its minimum element in O(log n).",
    ex: "[3,4,5,1,2] -> 1\n[4,5,6,7,0,1,2] -> 0",
    con: "",
  },
  {
    num: 33,
    diff: "medium",
    pattern: "Binary Search",
    slug: "search-in-rotated-sorted-array",
    title: "Search in Rotated Sorted Array",
    desc: "A sorted array of distinct values was rotated. Return the index of target, or -1, in O(log n).",
    ex: "nums = [4,5,6,7,0,1,2], target = 0 -> 4",
    con: "",
  },
  {
    num: 875,
    diff: "medium",
    pattern: "Binary Search",
    slug: "koko-eating-bananas",
    title: "Koko Eating Bananas",
    desc: "Koko eats k bananas per hour from a single pile each hour. Return the smallest integer speed k that finishes all piles within h hours.",
    ex: "piles = [3,6,7,11], h = 8 -> 4",
    con: "",
  },
  {
    num: 4,
    diff: "hard",
    pattern: "Binary Search",
    slug: "median-of-two-sorted-arrays",
    title: "Median of Two Sorted Arrays",
    desc: "Return the median of two sorted arrays. Target O(log(m+n)).",
    ex: "[1,3] and [2] -> 2.0\n[1,2] and [3,4] -> 2.5",
    con: "",
  },
  // ---- Linked List ----
  {
    num: 206,
    diff: "easy",
    pattern: "Linked List",
    slug: "reverse-linked-list",
    title: "Reverse Linked List",
    desc: "Reverse a singly linked list and return the new head.",
    ex: "1->2->3->4->5  ->  5->4->3->2->1",
    con: "",
  },
  {
    num: 21,
    diff: "easy",
    pattern: "Linked List",
    slug: "merge-two-sorted-lists",
    title: "Merge Two Sorted Lists",
    desc: "Merge two sorted linked lists into one sorted list by splicing the nodes together; return the head.",
    ex: "1->2->4 and 1->3->4  ->  1->1->2->3->4->4",
    con: "",
  },
  {
    num: 141,
    diff: "easy",
    pattern: "Linked List",
    slug: "linked-list-cycle",
    title: "Linked List Cycle",
    desc: "Return true if the linked list contains a cycle (a node reachable again by following next pointers).",
    ex: "3->2->0->-4 with the tail pointing back to node 2 -> true",
    con: "",
  },
  {
    num: 19,
    diff: "medium",
    pattern: "Linked List",
    slug: "remove-nth-node-from-end-of-list",
    title: "Remove Nth Node From End of List",
    desc: "Remove the n-th node from the end of the list and return the head. Try to do it in one pass.",
    ex: "1->2->3->4->5, n = 2  ->  1->2->3->5",
    con: "",
  },
  {
    num: 143,
    diff: "medium",
    pattern: "Linked List",
    slug: "reorder-list",
    title: "Reorder List",
    desc: "Reorder the list L0->L1->...->Ln as L0->Ln->L1->Ln-1->... in place, changing pointers not values.",
    ex: "1->2->3->4  ->  1->4->2->3",
    con: "",
  },
  {
    num: 146,
    diff: "medium",
    pattern: "Linked List",
    slug: "lru-cache",
    title: "LRU Cache",
    desc: "Design a cache with O(1) get and put and a fixed capacity; evict the least-recently-used entry when full.",
    ex: "capacity 2: put(1,1), put(2,2), get(1)->1, put(3,3) evicts 2, get(2)->-1",
    con: "",
  },
  {
    num: 23,
    diff: "hard",
    pattern: "Linked List",
    slug: "merge-k-sorted-lists",
    title: "Merge k Sorted Lists",
    desc: "Merge k sorted linked lists into a single sorted list and return its head.",
    ex: "[1->4->5, 1->3->4, 2->6]  ->  1->1->2->3->4->4->5->6",
    con: "",
  },
  // ---- Trees ----
  {
    num: 226,
    diff: "easy",
    pattern: "Trees",
    slug: "invert-binary-tree",
    title: "Invert Binary Tree",
    desc: "Swap every node's left and right child, and return the root of the mirrored tree.",
    ex: "[4,2,7,1,3,6,9] -> [4,7,2,9,6,3,1]",
    con: "",
  },
  {
    num: 104,
    diff: "easy",
    pattern: "Trees",
    slug: "maximum-depth-of-binary-tree",
    title: "Maximum Depth of Binary Tree",
    desc: "Return the number of nodes along the longest path from the root down to a leaf.",
    ex: "[3,9,20,null,null,15,7] -> 3",
    con: "",
  },
  {
    num: 572,
    diff: "easy",
    pattern: "Trees",
    slug: "subtree-of-another-tree",
    title: "Subtree of Another Tree",
    desc: "Return true if subRoot is a subtree of root — some node of root whose subtree matches subRoot exactly.",
    ex: "root = [3,4,5,1,2], subRoot = [4,1,2] -> true",
    con: "",
  },
  {
    num: 102,
    diff: "medium",
    pattern: "Trees",
    slug: "binary-tree-level-order-traversal",
    title: "Binary Tree Level Order Traversal",
    desc: "Return the node values level by level, left to right (breadth-first).",
    ex: "[3,9,20,null,null,15,7] -> [[3],[9,20],[15,7]]",
    con: "",
  },
  {
    num: 98,
    diff: "medium",
    pattern: "Trees",
    slug: "validate-binary-search-tree",
    title: "Validate Binary Search Tree",
    desc: "Return true if the tree is a valid BST: every node's whole left subtree is smaller and right subtree larger.",
    ex: "[2,1,3] -> true\n[5,1,4,null,null,3,6] -> false",
    con: "",
  },
  {
    num: 235,
    diff: "medium",
    pattern: "Trees",
    slug: "lowest-common-ancestor-of-a-binary-search-tree",
    title: "Lowest Common Ancestor of a BST",
    desc: "Given a BST and two of its nodes, return their lowest common ancestor.",
    ex: "root = [6,2,8,0,4,7,9], p = 2, q = 8 -> 6",
    con: "",
  },
  {
    num: 230,
    diff: "medium",
    pattern: "Trees",
    slug: "kth-smallest-element-in-a-bst",
    title: "Kth Smallest Element in a BST",
    desc: "Return the k-th smallest value (1-indexed) in a binary search tree.",
    ex: "root = [3,1,4,null,2], k = 1 -> 1",
    con: "",
  },
  {
    num: 105,
    diff: "medium",
    pattern: "Trees",
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
    title: "Construct Tree from Preorder and Inorder",
    desc: "Rebuild and return the binary tree given its preorder and inorder traversals (all values unique).",
    ex: "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]\n-> [3,9,20,null,null,15,7]",
    con: "",
  },
  {
    num: 297,
    diff: "hard",
    pattern: "Trees",
    slug: "serialize-and-deserialize-binary-tree",
    title: "Serialize and Deserialize Binary Tree",
    desc: "Design methods to encode a binary tree to a string and decode that string back to the identical tree.",
    ex: "[1,2,3,null,null,4,5]  ->  serialize  ->  deserialize  ->  [1,2,3,null,null,4,5]",
    con: "",
  },
  {
    num: 124,
    diff: "hard",
    pattern: "Trees",
    slug: "binary-tree-maximum-path-sum",
    title: "Binary Tree Maximum Path Sum",
    desc: "A path is any sequence of nodes connected by edges (it need not pass through the root). Return the maximum sum of node values along any path.",
    ex: "[-10,9,20,null,null,15,7] -> 42   (15 -> 20 -> 7)",
    con: "",
  },
  // ---- Tries ----
  {
    num: 208,
    diff: "medium",
    pattern: "Tries",
    slug: "implement-trie-prefix-tree",
    title: "Implement Trie (Prefix Tree)",
    desc: "Implement a prefix tree with insert(word), search(word) for an exact word, and startsWith(prefix).",
    ex: 'insert("apple"), search("apple")->true, search("app")->false, startsWith("app")->true',
    con: "",
  },
  {
    num: 211,
    diff: "medium",
    pattern: "Tries",
    slug: "design-add-and-search-words-data-structure",
    title: "Design Add and Search Words Data Structure",
    desc: "Support addWord and search, where a search string may contain '.' which matches any single letter.",
    ex: 'addWord("bad"), search("b..")->true, search(".ad")->true, search("pad")->false',
    con: "",
  },
  {
    num: 212,
    diff: "hard",
    pattern: "Tries",
    slug: "word-search-ii",
    title: "Word Search II",
    desc: "Given a letter grid and a word list, return all words that can be traced through adjacent (up/down/left/right) cells, each cell used once per word.",
    ex: 'board with words = ["oath","pea","eat","rain"] -> ["eat","oath"]',
    con: "",
  },
  // ---- Heaps / Priority Queue ----
  {
    num: 703,
    diff: "easy",
    pattern: "Heaps / Priority Queue",
    slug: "kth-largest-element-in-a-stream",
    title: "Kth Largest Element in a Stream",
    desc: "Design a class that, as values arrive, always returns the k-th largest element seen so far.",
    ex: "k = 3, start [4,5,8,2]; add(3)->4, add(5)->5, add(10)->5, add(9)->8, add(4)->8",
    con: "",
  },
  {
    num: 1046,
    diff: "easy",
    pattern: "Heaps / Priority Queue",
    slug: "last-stone-weight",
    title: "Last Stone Weight",
    desc: "Repeatedly smash the two heaviest stones; equal stones vanish, otherwise the difference remains. Return the last stone's weight, or 0.",
    ex: "[2,7,4,1,8,1] -> 1",
    con: "",
  },
  {
    num: 973,
    diff: "medium",
    pattern: "Heaps / Priority Queue",
    slug: "k-closest-points-to-origin",
    title: "K Closest Points to Origin",
    desc: "Return the k points closest to the origin by Euclidean distance, in any order.",
    ex: "points = [[1,3],[-2,2]], k = 1 -> [[-2,2]]",
    con: "",
  },
  {
    num: 215,
    diff: "medium",
    pattern: "Heaps / Priority Queue",
    slug: "kth-largest-element-in-an-array",
    title: "Kth Largest Element in an Array",
    desc: "Return the k-th largest element by value (duplicates counted). Consider a size-k heap or quickselect.",
    ex: "[3,2,1,5,6,4], k = 2 -> 5",
    con: "",
  },
  {
    num: 621,
    diff: "medium",
    pattern: "Heaps / Priority Queue",
    slug: "task-scheduler",
    title: "Task Scheduler",
    desc: "Given task labels and a cooldown n that must separate two identical tasks, return the least number of time units (including idles) to finish all tasks.",
    ex: "tasks = [A,A,A,B,B,B], n = 2 -> 8",
    con: "",
  },
  {
    num: 295,
    diff: "hard",
    pattern: "Heaps / Priority Queue",
    slug: "find-median-from-data-stream",
    title: "Find Median from Data Stream",
    desc: "Design a structure that adds numbers and returns the running median of all values so far, with O(log n) add.",
    ex: "add(1), add(2), findMedian()->1.5, add(3), findMedian()->2.0",
    con: "",
  },
  // ---- Backtracking ----
  {
    num: 78,
    diff: "medium",
    pattern: "Backtracking",
    slug: "subsets",
    title: "Subsets",
    desc: "Return all possible subsets (the power set) of an array of distinct integers, in any order.",
    ex: "[1,2,3] -> [[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]",
    con: "",
  },
  {
    num: 39,
    diff: "medium",
    pattern: "Backtracking",
    slug: "combination-sum",
    title: "Combination Sum",
    desc: "Return all unique combinations of the candidates (each may be reused any number of times) that sum to the target.",
    ex: "candidates = [2,3,6,7], target = 7 -> [[2,2,3],[7]]",
    con: "",
  },
  {
    num: 46,
    diff: "medium",
    pattern: "Backtracking",
    slug: "permutations",
    title: "Permutations",
    desc: "Return all permutations of an array of distinct integers.",
    ex: "[1,2,3] -> [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]",
    con: "",
  },
  {
    num: 79,
    diff: "medium",
    pattern: "Backtracking",
    slug: "word-search",
    title: "Word Search",
    desc: "Return true if the word can be traced through adjacent (up/down/left/right) cells of the grid, each cell used at most once.",
    ex: 'board = [[A,B,C,E],[S,F,C,S],[A,D,E,E]], word = "ABCCED" -> true',
    con: "",
  },
  {
    num: 131,
    diff: "medium",
    pattern: "Backtracking",
    slug: "palindrome-partitioning",
    title: "Palindrome Partitioning",
    desc: "Return every way to split the string so that each part is a palindrome.",
    ex: '"aab" -> [["a","a","b"],["aa","b"]]',
    con: "",
  },
  {
    num: 51,
    diff: "hard",
    pattern: "Backtracking",
    slug: "n-queens",
    title: "N-Queens",
    desc: "Place n queens on an n x n board so that no two share a row, column, or diagonal. Return all distinct board configurations.",
    ex: "n = 4 -> 2 distinct solutions",
    con: "",
  },
  // ---- Graphs ----
  {
    num: 733,
    diff: "easy",
    pattern: "Graphs",
    slug: "flood-fill",
    title: "Flood Fill",
    desc: "Starting from cell (sr, sc) in an image grid, repaint it and every same-colored cell reachable through the four cardinal directions with a new color; return the image.",
    ex: "image = [[1,1,1],[1,1,0],[1,0,1]], sr=1, sc=1, color=2 -> [[2,2,2],[2,2,0],[2,0,1]]",
    con: "",
  },
  {
    num: 200,
    diff: "medium",
    pattern: "Graphs",
    slug: "number-of-islands",
    title: "Number of Islands",
    desc: "Given a grid of '1' (land) and '0' (water), count the islands, where an island is land connected in the four cardinal directions.",
    ex: "a grid with 3 separate land clusters -> 3",
    con: "",
  },
  {
    num: 133,
    diff: "medium",
    pattern: "Graphs",
    slug: "clone-graph",
    title: "Clone Graph",
    desc: "Given a reference to a node in a connected undirected graph, return a deep copy of the whole graph.",
    ex: "adjList = [[2,4],[1,3],[2,4],[1,3]] -> an identical, independent graph",
    con: "",
  },
  {
    num: 994,
    diff: "medium",
    pattern: "Graphs",
    slug: "rotting-oranges",
    title: "Rotting Oranges",
    desc: "Each minute, every rotten orange (2) rots its fresh (1) neighbors in the four directions. Return the minutes until none are fresh, or -1 if impossible.",
    ex: "[[2,1,1],[1,1,0],[0,1,1]] -> 4",
    con: "",
  },
  {
    num: 417,
    diff: "medium",
    pattern: "Graphs",
    slug: "pacific-atlantic-water-flow",
    title: "Pacific Atlantic Water Flow",
    desc: "Water flows from a cell to equal-or-lower neighbors. Return the cells from which water can reach both the top/left (Pacific) and bottom/right (Atlantic) edges.",
    ex: "return the list of qualifying [row, col] coordinates",
    con: "",
  },
  {
    num: 207,
    diff: "medium",
    pattern: "Graphs",
    slug: "course-schedule",
    title: "Course Schedule",
    desc: "Given numCourses and prerequisite pairs [a,b] meaning b before a, return true if all courses can be finished (the dependency graph has no cycle).",
    ex: "numCourses = 2, prerequisites = [[1,0]] -> true\n[[1,0],[0,1]] -> false",
    con: "",
  },
  {
    num: 323,
    diff: "medium",
    pattern: "Graphs",
    slug: "number-of-connected-components-in-an-undirected-graph",
    title: "Number of Connected Components",
    desc: "Given n nodes and an undirected edge list, return the number of connected components.",
    ex: "n = 5, edges = [[0,1],[1,2],[3,4]] -> 2",
    con: "",
  },
  {
    num: 261,
    diff: "medium",
    pattern: "Graphs",
    slug: "graph-valid-tree",
    title: "Graph Valid Tree",
    desc: "Given n nodes and an undirected edge list, return true if they form a valid tree — fully connected with no cycle.",
    ex: "n = 5, edges = [[0,1],[0,2],[0,3],[1,4]] -> true",
    con: "",
  },
  {
    num: 127,
    diff: "hard",
    pattern: "Graphs",
    slug: "word-ladder",
    title: "Word Ladder",
    desc: "Transform beginWord into endWord one letter at a time; every intermediate word must be in the word list. Return the length of the shortest such sequence, or 0.",
    ex: "begin = \"hit\", end = \"cog\", list = [hot,dot,dog,lot,log,cog] -> 5",
    con: "",
  },
  {
    num: 269,
    diff: "hard",
    pattern: "Graphs",
    slug: "alien-dictionary",
    title: "Alien Dictionary",
    desc: 'Given words sorted by the rules of an unknown alphabet, return any letter order consistent with them, or "" if none exists.',
    ex: '["wrt","wrf","er","ett","rftt"] -> "wertf"',
    con: "",
  },
  // ---- Intervals ----
  {
    num: 56,
    diff: "medium",
    pattern: "Intervals",
    slug: "merge-intervals",
    title: "Merge Intervals",
    desc: "Merge all overlapping intervals and return the resulting non-overlapping intervals.",
    ex: "[[1,3],[2,6],[8,10],[15,18]] -> [[1,6],[8,10],[15,18]]",
    con: "",
  },
  {
    num: 57,
    diff: "medium",
    pattern: "Intervals",
    slug: "insert-interval",
    title: "Insert Interval",
    desc: "Given sorted, non-overlapping intervals, insert a new interval and merge as needed.",
    ex: "intervals = [[1,3],[6,9]], newInterval = [2,5] -> [[1,5],[6,9]]",
    con: "",
  },
  {
    num: 435,
    diff: "medium",
    pattern: "Intervals",
    slug: "non-overlapping-intervals",
    title: "Non-overlapping Intervals",
    desc: "Return the minimum number of intervals to remove so that the rest do not overlap.",
    ex: "[[1,2],[2,3],[3,4],[1,3]] -> 1",
    con: "",
  },
  {
    num: 253,
    diff: "medium",
    pattern: "Intervals",
    slug: "meeting-rooms-ii",
    title: "Meeting Rooms II",
    desc: "Given meeting start/end times, return the minimum number of rooms needed to hold all of them.",
    ex: "[[0,30],[5,10],[15,20]] -> 2",
    con: "",
  },
  // ---- Greedy ----
  {
    num: 53,
    diff: "medium",
    pattern: "Greedy",
    slug: "maximum-subarray",
    title: "Maximum Subarray",
    desc: "Return the largest sum of any contiguous subarray (Kadane's algorithm).",
    ex: "[-2,1,-3,4,-1,2,1,-5,4] -> 6   ([4,-1,2,1])",
    con: "",
  },
  {
    num: 55,
    diff: "medium",
    pattern: "Greedy",
    slug: "jump-game",
    title: "Jump Game",
    desc: "Each value is the maximum jump length from that index. Return true if you can reach the last index.",
    ex: "[2,3,1,1,4] -> true\n[3,2,1,0,4] -> false",
    con: "",
  },
  {
    num: 45,
    diff: "medium",
    pattern: "Greedy",
    slug: "jump-game-ii",
    title: "Jump Game II",
    desc: "Each value is the maximum jump from that index (the last index is always reachable). Return the minimum number of jumps to reach it.",
    ex: "[2,3,1,1,4] -> 2",
    con: "",
  },
  {
    num: 134,
    diff: "medium",
    pattern: "Greedy",
    slug: "gas-station",
    title: "Gas Station",
    desc: "gas[i] is fuel at station i and cost[i] is fuel to reach the next. Return the starting index that lets you complete the circular route once, or -1.",
    ex: "gas = [1,2,3,4,5], cost = [3,4,5,1,2] -> 3",
    con: "",
  },
  {
    num: 846,
    diff: "medium",
    pattern: "Greedy",
    slug: "hand-of-straights",
    title: "Hand of Straights",
    desc: "Given a hand of cards and a group size, return true if the hand can be rearranged into groups of that many consecutive cards.",
    ex: "hand = [1,2,3,6,2,3,4,7,8], groupSize = 3 -> true",
    con: "",
  },
  // ---- Dynamic Programming ----
  {
    num: 70,
    diff: "easy",
    pattern: "Dynamic Programming",
    slug: "climbing-stairs",
    title: "Climbing Stairs",
    desc: "You climb 1 or 2 steps at a time. Return the number of distinct ways to reach step n.",
    ex: "n = 3 -> 3   (1+1+1, 1+2, 2+1)",
    con: "",
  },
  {
    num: 198,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "house-robber",
    title: "House Robber",
    desc: "You cannot rob two adjacent houses. Return the maximum money you can rob along the street.",
    ex: "[2,7,9,3,1] -> 12   (2 + 9 + 1)",
    con: "",
  },
  {
    num: 213,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "house-robber-ii",
    title: "House Robber II",
    desc: "Like House Robber, but the houses are in a circle, so the first and last are adjacent.",
    ex: "[2,3,2] -> 3\n[1,2,3,1] -> 4",
    con: "",
  },
  {
    num: 322,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "coin-change",
    title: "Coin Change",
    desc: "Given coin denominations and an amount, return the fewest coins that sum to it, or -1 if impossible.",
    ex: "coins = [1,2,5], amount = 11 -> 3   (5 + 5 + 1)",
    con: "",
  },
  {
    num: 300,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    desc: "Return the length of the longest strictly increasing subsequence.",
    ex: "[10,9,2,5,3,7,101,18] -> 4   ([2,3,7,101])",
    con: "",
  },
  {
    num: 139,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "word-break",
    title: "Word Break",
    desc: "Return true if s can be segmented into a sequence of dictionary words (words may be reused).",
    ex: 's = "leetcode", dict = ["leet","code"] -> true',
    con: "",
  },
  {
    num: 91,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "decode-ways",
    title: "Decode Ways",
    desc: 'Letters A..Z map to "1".."26". Return the number of ways to decode a digit string.',
    ex: '"226" -> 3   ("BZ","VF","BBF")',
    con: "",
  },
  {
    num: 5,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    desc: "Return the longest contiguous substring of s that is a palindrome.",
    ex: '"babad" -> "bab" (or "aba")\n"cbbd" -> "bb"',
    con: "",
  },
  {
    num: 62,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "unique-paths",
    title: "Unique Paths",
    desc: "A robot moves only right or down on an m x n grid from the top-left to the bottom-right. Return the number of unique paths.",
    ex: "m = 3, n = 7 -> 28",
    con: "",
  },
  {
    num: 1143,
    diff: "medium",
    pattern: "Dynamic Programming",
    slug: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    desc: "Return the length of the longest subsequence common to both strings (characters in order, not necessarily contiguous).",
    ex: '"abcde", "ace" -> 3   ("ace")',
    con: "",
  },
  // ---- Bit Manipulation / Math ----
  {
    num: 136,
    diff: "easy",
    pattern: "Bit Manipulation / Math",
    slug: "single-number",
    title: "Single Number",
    desc: "Every element appears twice except one. Return the single element, ideally in O(1) space (XOR cancels pairs).",
    ex: "[4,1,2,1,2] -> 4",
    con: "",
  },
  {
    num: 191,
    diff: "easy",
    pattern: "Bit Manipulation / Math",
    slug: "number-of-1-bits",
    title: "Number of 1 Bits",
    desc: "Return the number of set bits (population count) in an unsigned integer.",
    ex: "n = 11 (binary 1011) -> 3",
    con: "",
  },
  {
    num: 338,
    diff: "easy",
    pattern: "Bit Manipulation / Math",
    slug: "counting-bits",
    title: "Counting Bits",
    desc: "Return an array where result[i] is the number of set bits in i, for every i from 0 to n.",
    ex: "n = 5 -> [0,1,1,2,1,2]",
    con: "",
  },
  {
    num: 268,
    diff: "easy",
    pattern: "Bit Manipulation / Math",
    slug: "missing-number",
    title: "Missing Number",
    desc: "The array holds n distinct numbers drawn from 0..n. Return the one number in that range that is missing.",
    ex: "[3,0,1] -> 2\n[0,1] -> 2",
    con: "",
  },
  {
    num: 190,
    diff: "easy",
    pattern: "Bit Manipulation / Math",
    slug: "reverse-bits",
    title: "Reverse Bits",
    desc: "Reverse the 32 bits of an unsigned integer and return the result.",
    ex: "n = 43261596 -> 964176192   (bit pattern reversed)",
    con: "",
  },
];

export const PROBLEMS: Problem[] = RAW.map(build);

export function getProblem(id: string): Problem | undefined {
  return PROBLEMS.find((p) => p.id === id);
}

export function problemsByPattern(): { pattern: string; items: Problem[] }[] {
  const order: string[] = [];
  const map = new Map<string, Problem[]>();
  for (const p of PROBLEMS) {
    if (!map.has(p.pattern)) {
      map.set(p.pattern, []);
      order.push(p.pattern);
    }
    map.get(p.pattern)!.push(p);
  }
  return order.map((pattern) => ({ pattern, items: map.get(pattern)! }));
}

function htmlToText(html: string): string {
  return html
    .replace(/<h4>(.*?)<\/h4>/g, "\n\n**$1**\n\n")
    .replace(/<pre>([\s\S]*?)<\/pre>/g, (_m, c) => "\n```\n" + c.trim() + "\n```\n")
    .replace(/<\/p>/g, "\n\n")
    .replace(/<[^>]+>/g, "")
    .trim();
}

export function formatProblemMarkdown(p: Problem): string {
  const diff = p.diff.charAt(0).toUpperCase() + p.diff.slice(1);
  return `# #${p.num} ${p.title}\n\n**${diff} · ${p.pattern}**\n\n${htmlToText(p.descHtml)}\n\n[Reference · LeetCode #${p.num}](${p.url})\n`;
}
